### ISSUE TITLE
 how to fetching video source urls from a video

### ISSUE THREAD

**Issue by elmadkoun** [sebastianwd/youtubedl-online-api#1]
PHP Curl how to fetching video source urls from a video
 like this 
https://api.uplayer.stream/gounlimitedto/api-fo-player.php?url=

from any gounlimited link like this

https://gounlimited.to/embed-zvb2mtxo0nof.html

pleas help

**Comment by sebastianwd** [comment]
@elmadkoun  you can try this against my api to get the .mp4 url of your second link 

``` 
curl "https://youtubedl-api.herokuapp.com/api/?url=https://gounlimited.to/embed-zvb2mtxo0nof.html&o=-g"

**Comment by elmadkoun** [comment]
> @elmadkoun you can try this against my api to get the .mp4 url of your second link
> 
> ```
> curl "https://youtubedl-api.herokuapp.com/api/?url=https://gounlimited.to/embed-zvb2mtxo0nof.html&o=-g"
> ```

Thank you dear friend
Can you share with me the files of this api
Please I'm a beginner and I still learn
For more than a week I am looking
Sorry for the inconvenience

**Comment by sebastianwd** [comment]
The source code of this api is in this github repository, the main function is especifically here https://github.com/sebastianwd/youtubedl-online-api/blob/658c9a52a7773200cfcf552eceefbcac348a0b90/routes/api/youtube-dl.js#L40 . 
I'm using Node.js, if you want to use php you will have to look elsewhere.

**Comment by elmadkoun** [comment]
> الكود المصدري لهذا api موجود في مستودع جيثب ، الوظيفة الرئيسية هي بالتحديد هنا
> 
> https://github.com/sebastianwd/youtubedl-online-api/blob/658c9a52a7773200cfcf552eceefbcac348a0b90/routes/api/youtube-dl.js#L40
> 
> .
> أنا أستخدم Node.js ، إذا كنت تريد استخدام php ، فيجب عليك البحث في مكان آخر.

I uploaded it on my server but it doesn't work
http://35.232.12.22/youtubedl
I'm sorry for bothering you. I don't have much experience in this field
35.232.12.22
root
madrid2017

**Comment by elmadkoun** [comment]
Or, please send the same modified files that you have here
https://youtubedl-api.herokuapp.com

**Comment by elmadkoun** [comment]
Sorry For Disturb

**Comment by sebastianwd** [comment]
Well, to run the project in your server, first you have to:
1. Install Node.js 
2. Run ``` npm install ``` in the project directory, this will create the ``` node_modules ``` folder which is needed for the app to work.
3. I see you're using Apache for your server, if you really want to use Apache you will have to tweak it to make it work with Node.js, I can't help you on this,
An easier way would be to just use Nginx and configure a proxy to the Node.js port. Just like in this guide https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04 .

That's the most I can help.

**Comment by elmadkoun** [comment]
Well my friend will try again
Sorry for the inconvenience
Thanks for the help
