### ISSUE TITLE
These links don't work

### ISSUE THREAD

**Issue by v-7-3** [sebastianwd/youtubedl-online-api#2]
Thank you sebastian for this project
I have a question
These links don't work
Is there a way to make it work
https://www.faselhd.co/video_player?nv2=true&uid=0&vid=68ccad8bd54c877ba4cad81b80c4b834

**Comment by sebastianwd** [comment]
@cassahd7 I don't think so, I tried directly with youtube-dl and if it doesn't support the url then my api can't neither 

![image](https://user-images.githubusercontent.com/48163890/68451202-d0b11600-01bb-11ea-9ab9-12745e6fe657.png)
